In [270]:
import pandas as pd
from datetime import datetime
import pandas_datareader.data as web
import pandas_datareader as pdr

path = "./"
t = pd.HDFStore(path + "tickers.hd5", "r")
tickers = t["data"]
t.close()


for ticker in tickers['ticker']:
    f = web.DataReader(ticker, "av-daily-adjusted", api_key='88C5GJD6EJF4QHYA')
    f.index = pd.to_datetime(f.index)
    t = pd.HDFStore(path + ticker +".hd5", "w")
    t["data"] = f
    t.close()

In [6]:
import pandas as pd
from datetime import datetime
import pandas_datareader.data as web
import pandas_datareader as pdr
path = "./"
def load_data(ticker):
    t = pd.HDFStore(path + ticker +".hd5", "r")
    f = t["data"]
    t.close()
    return f

f = load_data("AAPL")
f

,open,high,low,close,adjusted close,volume,dividend amount,split coefficient
1999-10-04,62.375,64.875,62.375,64.563,2.0123,114839200,0.0,1.0
1999-10-05,65.625,68.125,64.750,67.938,2.1175,203551600,0.0,1.0
1999-10-06,69.375,69.625,67.000,67.188,2.0941,201068000,0.0,1.0
1999-10-07,68.438,68.625,64.875,66.375,2.0688,151471600,0.0,1.0
1999-10-08,66.188,66.313,63.500,65.563,2.0435,95701200,0.0,1.0
...,...,...,...,...,...,...,...,...
2019-09-23,218.950,219.840,217.650,218.720,218.7200,19165500,0.0,1.0
2019-09-24,221.030,222.490,217.190,217.680,217.6800,31190800,0.0,1.0
2019-09-25,218.550,221.500,217.140,221.030,221.0300,21903400,0.0,1.0
2019-09-26,220.000,220.940,218.830,219.890,219.8900,18833500,0.0,1.0
2019-09-27,220.540,220.960,217.280,218.820,218.8200,25352000,0.0,1.0

In [5]:
f.close()